from typing import Protocol

from app.schemas.response import (
    AlertResponse,
    DistributionResponse,
    DiskTimelineResponse,
    DiskTopResponse,
    HeatmapResponse,
    HostInfo,
    NetLoadResponse,
    OverviewResponse,
    SparklineResponse,
    TrendResponse,
)


class DataSource(Protocol):
    def get_overview(self) -> OverviewResponse: ...
    def get_hosts(self) -> list[HostInfo]: ...
    def get_distribution(self) -> DistributionResponse: ...
    def get_pref_trend(self, hostid: str | None = None) -> TrendResponse: ...
    def get_cpu_heatmap(self) -> HeatmapResponse: ...
    def get_disk_top(self) -> DiskTopResponse: ...
    def get_disk_timeline(self, hostid: str | None = None) -> DiskTimelineResponse: ...
    def get_alerts(self) -> AlertResponse: ...
    def get_sparklines(self) -> SparklineResponse: ...
    def get_net_load(self) -> NetLoadResponse: ...
    def get_disk_gauges(self, hostid: str | None = None) -> list[dict]: ...
